variables:
  JAVA_VERSION: 11

include:
  - local: '/templates/java/default.yaml'
  - local: '/templates/java/11.yaml'
  - local: '/templates/build_docker/default.yaml'
  - local: '/templates/deploy/deploy_default.yaml'
    rules:
      - if: $CI_PROJECT_NAME == "java-11-app-1"
  - local: '/templates/deploy/java_default.yaml'
    rules:
      - if: $CI_PROJECT_NAME == "java-11-app-2"

stages:
  - build
  - test
  - build_docker
  - deploy

build:
  extends: .default_build

test:
  extends: .default_test
  except:
    variables:
      - $CI_PROJECT_NAME == "java-11-app-1"
      - $SKIP_TESTS != "false"

test_kafka_mongo:
  extends: .test11_kafka_mongo
  rules:
    - if: $SKIP_TESTS != "false"
      when: never
    - if: $CI_PROJECT_NAME == "java-11-app-1"

test_java-11-app-2:
  extends: .test11_java-11-app-2
  rules:
    - if: $SKIP_TESTS != "false"
      when: never
    - if: $CI_PROJECT_NAME == "java-11-app-2"

build_docker:
  extends: .default_build_docker

# deploy is there /templates/deploy/deploy_default.yaml
