variables:
  JAVA_VERSION: 17

include:
  - local: '/templates/java/default.yaml'
  - local: '/templates/java/17.yaml'
  - local: '/templates/build_docker/default.yaml'
  - local: '/templates/deploy/deploy_default.yaml'

stages:
  - build
  - test
  - build_docker
  - deploy

build:
  extends: .default_build

test_default:
  extends: .default_test
  except:
    variables:
      - $CI_PROJECT_NAME == "java-17-app-1"
      - $SKIP_TESTS != "false"

test_java-17-app-2:
  extends: .test17_java-17-app-2
  rules:
    - if: $SKIP_TESTS != "false"
      when: never
    - if: $CI_PROJECT_NAME == "java-17-app-2"

test_java-17-app-1:
  extends: .test17_auth_svc
  rules:
    - if: $SKIP_TESTS != "false"
      when: never
    - if: $CI_PROJECT_NAME == "java-17-app-1"

test_java-17-app-3:
  extends: .test17_java-17-app-3
  rules:
    - if: $SKIP_TESTS != "false"
      when: never
    - if: $CI_PROJECT_NAME == "java-17-app-3"

build_docker:
  extends: .default_build_docker

# deploy is there /templates/deploy/deploy_default.yaml
